apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    envivronment: dev
    project: expense
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9