apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: digital
    environment: dev
    tier: frontend
spec:
  containers:
    - name: labels
      image: nginx
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
