apiVersion: v1
kind: Pod
metadata: 
  name: annotations
  labels:
    environment: dev
    project: digital
    tier: frontend
  annotations:
    buildUrl: "https://jenkins.dev.devops.com/build/7"
    imageRegistry: "hub.docker.com"
spec: 
  containers:
    - name: nginx
      image: nginx