apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    project: digital
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 120m
          memory: 120Mi
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]

# the requested --vm-bytes is bigger than the resources we configured . resulted in CrashLoopBackOff