apiVersion: v1
kind: Pod
metadata:
  name: cm-util
  labels:
    project: digital
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              key: cm
              name: course
        - name: duration
          valueFrom:
            configMapKeyRef:
              key: cm
              name: duration