apiVersion: v1
kind: Pod
metadata:
  name: cm-util
  labels:
    project: digital
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: cm
      # env:
      #   - name: course
      #     valueFrom:
      #       configMapKeyRef:
      #         key: course
      #         name: cm
      #   - name: duration
      #     valueFrom:
      #       configMapKeyRef:
      #         key: duration
      #         name: cm