apiVersion: v1
kind: Pod
metadata:
  name: secret-util
  labels:
    project: digital
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret