apiVersion: v1
kind: Pod
metadata:
  name: svc-util
  labels:
    environment: dev
    project: digital
spec:
  containers:
    - name: svc-util
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-util
spec:
  type: NodePort
  selector:
    environment: dev
    project: digital
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32007