apiVersion: v1
kind: Pod
metadata:
  name: svc-np
  labels:
    environment: dev
    project: digital
spec:
  containers:
    - name: svc-np
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-np
spec:
  type: NodePort
  selector:
    environment: dev
    project: digital
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32007