apiVersion: v1
kind: Pod
metadata:
  name: svc-lb
  labels:
    environment: dev
    project: digital
spec:
  containers:
    - name: svc-lb
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-lb
spec:
  type: LoadBalancer
  selector:
    environment: dev
    project: digital
  ports:
    - port: 80
      targetPort: 80