apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dplymnt
  labels:
    project: digital
    environment: dev
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: digital
      environment: dev
      app: frontend
  template:
    metadata:
      name: nginx-dplymnt
      labels:
        project: digital
        environment: dev
        app: frontend
    spec:
      containers:
        - name: nginx-dplymnt
          image: nginx:alpine-slim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dplymnt
  labels:
    project: digital
    environment: dev
    app: frontend
spec:
  type: LoadBalancer
  selector:
    project: digital
    environment: dev
    app: frontend
  ports:
    - port: 80  
      targetPort: 80
      nodePort: 32008